from abc import ABC, abstractmethod
from typing import List


class EmbeddingProviderInterface(ABC):
    """Interface for embedding providers to generate vector embeddings."""

    @abstractmethod
    async def generate_embedding(self, text: str) -> List[float]:
        """
        Generate vector embedding for a single text input.

        Args:
            text: The text to generate embeddings for

        Returns:
            List of float values representing the vector embedding
        """
        pass

    @abstractmethod
    async def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate vector embeddings for multiple text inputs.

        Args:
            texts: List of texts to generate embeddings for

        Returns:
            List of embedding vectors, each represented as List[float]
        """
        pass

    @abstractmethod
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension size of embeddings generated by this provider.

        Returns:
            The dimension size (number of float values) in each embedding vector
        """
        pass

    @abstractmethod
    def get_model_name(self) -> str:
        """
        Get the name of the embedding model being used.

        Returns:
            The model name string
        """
        pass
