"""matrix models

Revision ID: e4f00ee29b19
Revises: 
Create Date: 2025-07-21 15:55:24.327010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4f00ee29b19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrices',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrices_id'), 'matrices', ['id'], unique=False)
    op.create_index(op.f('ix_matrices_name'), 'matrices', ['name'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('matrix_id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_storage_key'), 'documents', ['storage_key'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('matrix_id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('matrix_cells',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('matrix_id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('question_id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='matrixcellstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_cells_id'), 'matrix_cells', ['id'], unique=False)
    op.create_table('qa_jobs',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('matrix_cell_id', sa.BigInteger().with_variant(mysql.BIGINT(), 'mysql').with_variant(sa.BIGINT(), 'postgresql').with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='qajobstatus'), nullable=False),
    sa.Column('worker_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matrix_cell_id'], ['matrix_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_jobs_id'), 'qa_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_jobs_id'), table_name='qa_jobs')
    op.drop_table('qa_jobs')
    op.drop_index(op.f('ix_matrix_cells_id'), table_name='matrix_cells')
    op.drop_table('matrix_cells')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_documents_storage_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_matrices_name'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_id'), table_name='matrices')
    op.drop_table('matrices')
    
    # Drop ENUMs that were created
    op.execute("DROP TYPE IF EXISTS matrixcellstatus")
    op.execute("DROP TYPE IF EXISTS qajobstatus")
    # ### end Alembic commands ###
