from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, ConfigDict
from pydantic.alias_generators import to_camel


class ExecutionTriggerRequest(BaseModel):
    """Request to trigger a workflow execution"""

    trigger_context: Optional[Dict[str, Any]] = Field(
        None, description="Additional context for the execution trigger"
    )

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class ExecutionFileResponse(BaseModel):
    """Response model for an execution file"""

    id: int = Field(..., description="File ID")
    name: str = Field(..., description="File name")
    file_type: str = Field(..., description="File type (output or scratch)")
    file_size: int = Field(..., description="File size in bytes")
    storage_path: str = Field(..., description="Storage path")
    mime_type: Optional[str] = Field(None, description="MIME type")
    created_at: datetime = Field(..., description="When file was created")

    model_config = ConfigDict(
        from_attributes=True, alias_generator=to_camel, populate_by_name=True
    )


class GeneratedFileResponse(BaseModel):
    """Response model for a generated file"""

    name: str = Field(..., description="File name")
    size: int = Field(..., description="File size in bytes")
    storage_key: Optional[str] = Field(None, description="S3 storage key")
    content_type: Optional[str] = Field(None, description="MIME type")

    model_config = ConfigDict(
        from_attributes=True, alias_generator=to_camel, populate_by_name=True
    )


class ExecutionResponse(BaseModel):
    """Response model for workflow execution"""

    execution_id: int = Field(..., alias="id", description="Execution ID")
    workflow_id: int = Field(..., description="Workflow ID")
    status: str = Field(
        ..., description="Execution status (pending, running, completed, failed)"
    )
    started_at: datetime = Field(..., description="When execution started")
    completed_at: Optional[datetime] = Field(
        None, description="When execution completed"
    )
    generated_files: Optional[List[GeneratedFileResponse]] = Field(
        None, description="Files generated by the execution"
    )
    total_size_bytes: Optional[int] = Field(
        None, description="Total size of all generated files"
    )
    error_message: Optional[str] = Field(
        None, description="Error message if execution failed"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None, description="Additional execution metadata"
    )

    model_config = ConfigDict(
        from_attributes=True, alias_generator=to_camel, populate_by_name=True
    )


class ExecutionStartedResponse(BaseModel):
    """Response when execution is started"""

    execution_id: int
    workflow_id: int
    status: str
    started_at: datetime

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class GenerateUploadUrlsRequest(BaseModel):
    """Request to generate presigned upload URLs for output files"""

    filenames: List[str] = Field(..., description="List of filenames to upload")

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class GenerateUploadUrlsResponse(BaseModel):
    """Response with presigned upload URLs for each file"""

    upload_urls: Dict[str, str] = Field(
        ..., description="Mapping of filename to presigned upload URL"
    )
    manifest_upload_url: str = Field(
        ..., description="Presigned upload URL for manifest file"
    )

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class UploadFileResponse(BaseModel):
    """Response after uploading a file"""

    filename: str = Field(..., description="Name of uploaded file")
    size: int = Field(..., description="File size in bytes")
    storage_path: str = Field(..., description="Storage path where file was uploaded")

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class UploadManifestRequest(BaseModel):
    """Request to upload execution manifest"""

    manifest: Dict[str, Any] = Field(..., description="Execution manifest JSON")

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class UploadManifestResponse(BaseModel):
    """Response after uploading manifest"""

    storage_path: str = Field(
        ..., description="Storage path where manifest was uploaded"
    )
    success: bool = Field(..., description="Whether upload succeeded")

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)
