// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ChatCompletionMessageToolCall
 * Represents a tool call in a chat completion message.
 */
export type ChatCompletionMessageToolCall = {
    /**
     * Id
     */
    id: string;
    function: _Function;
    /**
     * Type
     */
    type: 'function';
};

/**
 * ConversationCreate
 */
export type ConversationCreate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Extradata
     */
    extraData?: {
        [key: string]: unknown;
    } | null;
    /**
     * Aimodelid
     */
    aiModelId?: number | null;
};

/**
 * ConversationResponse
 */
export type ConversationResponse = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Extradata
     */
    extraData?: {
        [key: string]: unknown;
    } | null;
    /**
     * Aimodelid
     */
    aiModelId?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Isactive
     */
    isActive?: boolean;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * ConversationUpdate
 */
export type ConversationUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Extradata
     */
    extraData?: {
        [key: string]: unknown;
    } | null;
    /**
     * Aimodelid
     */
    aiModelId?: number | null;
    /**
     * Isactive
     */
    isActive?: boolean | null;
};

/**
 * Function
 * Represents a function call.
 */
export type _Function = {
    /**
     * Arguments
     */
    arguments: string;
    /**
     * Name
     */
    name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageCreate
 */
export type MessageCreate = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Toolcalls
     */
    toolCalls?: Array<ChatCompletionMessageToolCall> | null;
    /**
     * Toolcallid
     */
    toolCallId?: string | null;
    permissionMode?: ToolPermission;
    /**
     * Extradata
     */
    extraData?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Toolcalls
     */
    toolCalls?: Array<ChatCompletionMessageToolCall> | null;
    /**
     * Toolcallid
     */
    toolCallId?: string | null;
    permissionMode?: ToolPermission;
    /**
     * Extradata
     */
    extraData?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: number;
    /**
     * Conversationid
     */
    conversationId: number;
    /**
     * Sequencenumber
     */
    sequenceNumber: number;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * ToolDefinition
 */
export type ToolDefinition = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Parameters
     */
    parameters: {
        [key: string]: unknown;
    };
};

/**
 * ToolExecutionRequest
 */
export type ToolExecutionRequest = {
    /**
     * Tool Name
     */
    tool_name: string;
    /**
     * Parameters
     */
    parameters: {
        [key: string]: unknown;
    };
};

/**
 * ToolExecutionResponse
 */
export type ToolExecutionResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Result
     */
    result?: unknown;
    /**
     * Error
     */
    error?: string;
};

/**
 * ToolPermission
 */
export type ToolPermission = 'read' | 'write';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetActiveConversationsApiV1AgentsConversationsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agents/conversations/';
};

export type GetActiveConversationsApiV1AgentsConversationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActiveConversationsApiV1AgentsConversationsGetError = GetActiveConversationsApiV1AgentsConversationsGetErrors[keyof GetActiveConversationsApiV1AgentsConversationsGetErrors];

export type GetActiveConversationsApiV1AgentsConversationsGetResponses = {
    /**
     * Response Get Active Conversations Api V1 Agents Conversations  Get
     * Successful Response
     */
    200: Array<ConversationResponse>;
};

export type GetActiveConversationsApiV1AgentsConversationsGetResponse = GetActiveConversationsApiV1AgentsConversationsGetResponses[keyof GetActiveConversationsApiV1AgentsConversationsGetResponses];

export type CreateConversationApiV1AgentsConversationsPostData = {
    body: ConversationCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agents/conversations/';
};

export type CreateConversationApiV1AgentsConversationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationApiV1AgentsConversationsPostError = CreateConversationApiV1AgentsConversationsPostErrors[keyof CreateConversationApiV1AgentsConversationsPostErrors];

export type CreateConversationApiV1AgentsConversationsPostResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type CreateConversationApiV1AgentsConversationsPostResponse = CreateConversationApiV1AgentsConversationsPostResponses[keyof CreateConversationApiV1AgentsConversationsPostResponses];

export type DeleteConversationApiV1AgentsConversationsConversationIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Conversationid
         */
        conversationId: number;
    };
    query?: never;
    url: '/api/v1/agents/conversations/{conversationId}';
};

export type DeleteConversationApiV1AgentsConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiV1AgentsConversationsConversationIdDeleteError = DeleteConversationApiV1AgentsConversationsConversationIdDeleteErrors[keyof DeleteConversationApiV1AgentsConversationsConversationIdDeleteErrors];

export type DeleteConversationApiV1AgentsConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConversationApiV1AgentsConversationsConversationIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Conversationid
         */
        conversationId: number;
    };
    query?: never;
    url: '/api/v1/agents/conversations/{conversationId}';
};

export type GetConversationApiV1AgentsConversationsConversationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationApiV1AgentsConversationsConversationIdGetError = GetConversationApiV1AgentsConversationsConversationIdGetErrors[keyof GetConversationApiV1AgentsConversationsConversationIdGetErrors];

export type GetConversationApiV1AgentsConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type GetConversationApiV1AgentsConversationsConversationIdGetResponse = GetConversationApiV1AgentsConversationsConversationIdGetResponses[keyof GetConversationApiV1AgentsConversationsConversationIdGetResponses];

export type UpdateConversationApiV1AgentsConversationsConversationIdPatchData = {
    body: ConversationUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Conversationid
         */
        conversationId: number;
    };
    query?: never;
    url: '/api/v1/agents/conversations/{conversationId}';
};

export type UpdateConversationApiV1AgentsConversationsConversationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConversationApiV1AgentsConversationsConversationIdPatchError = UpdateConversationApiV1AgentsConversationsConversationIdPatchErrors[keyof UpdateConversationApiV1AgentsConversationsConversationIdPatchErrors];

export type UpdateConversationApiV1AgentsConversationsConversationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type UpdateConversationApiV1AgentsConversationsConversationIdPatchResponse = UpdateConversationApiV1AgentsConversationsConversationIdPatchResponses[keyof UpdateConversationApiV1AgentsConversationsConversationIdPatchResponses];

export type GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Conversationid
         */
        conversationId: number;
    };
    query?: never;
    url: '/api/v1/agents/conversations/{conversationId}/messages/';
};

export type GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetError = GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetErrors[keyof GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetErrors];

export type GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetResponses = {
    /**
     * Response Get Conversation Messages Api V1 Agents Conversations  Conversationid  Messages  Get
     * Successful Response
     */
    200: Array<MessageResponse>;
};

export type GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetResponse = GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetResponses[keyof GetConversationMessagesApiV1AgentsConversationsConversationIdMessagesGetResponses];

export type SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostData = {
    body: MessageCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Conversationid
         */
        conversationId: number;
    };
    query?: never;
    url: '/api/v1/agents/conversations/{conversationId}/messages/';
};

export type SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostError = SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostErrors[keyof SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostErrors];

export type SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostResponses = {
    /**
     * Response Send Message To Agent Api V1 Agents Conversations  Conversationid  Messages  Post
     * Successful Response
     */
    200: Array<MessageResponse>;
};

export type SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostResponse = SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostResponses[keyof SendMessageToAgentApiV1AgentsConversationsConversationIdMessagesPostResponses];

export type AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostData = {
    body: MessageCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path: {
        /**
         * Conversationid
         */
        conversationId: number;
    };
    query?: never;
    url: '/api/v1/agents/conversations/{conversationId}/messages/manual/';
};

export type AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostError = AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostErrors[keyof AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostErrors];

export type AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostResponse = AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostResponses[keyof AddManualMessageApiV1AgentsConversationsConversationIdMessagesManualPostResponses];

export type GetAvailableToolsApiV1AgentsToolsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agents/tools/';
};

export type GetAvailableToolsApiV1AgentsToolsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAvailableToolsApiV1AgentsToolsGetError = GetAvailableToolsApiV1AgentsToolsGetErrors[keyof GetAvailableToolsApiV1AgentsToolsGetErrors];

export type GetAvailableToolsApiV1AgentsToolsGetResponses = {
    /**
     * Response Get Available Tools Api V1 Agents Tools  Get
     * Successful Response
     */
    200: Array<ToolDefinition>;
};

export type GetAvailableToolsApiV1AgentsToolsGetResponse = GetAvailableToolsApiV1AgentsToolsGetResponses[keyof GetAvailableToolsApiV1AgentsToolsGetResponses];

export type GetToolsOpenaiFormatApiV1AgentsToolsOpenaiFormatGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agents/tools/openai-format/';
};

export type GetToolsOpenaiFormatApiV1AgentsToolsOpenaiFormatGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetToolsOpenaiFormatApiV1AgentsToolsOpenaiFormatGetError = GetToolsOpenaiFormatApiV1AgentsToolsOpenaiFormatGetErrors[keyof GetToolsOpenaiFormatApiV1AgentsToolsOpenaiFormatGetErrors];

export type GetToolsOpenaiFormatApiV1AgentsToolsOpenaiFormatGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExecuteToolApiV1AgentsToolsExecutePostData = {
    body: ToolExecutionRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Api-Key
         */
        'x-api-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/agents/tools/execute/';
};

export type ExecuteToolApiV1AgentsToolsExecutePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteToolApiV1AgentsToolsExecutePostError = ExecuteToolApiV1AgentsToolsExecutePostErrors[keyof ExecuteToolApiV1AgentsToolsExecutePostErrors];

export type ExecuteToolApiV1AgentsToolsExecutePostResponses = {
    /**
     * Successful Response
     */
    200: ToolExecutionResponse;
};

export type ExecuteToolApiV1AgentsToolsExecutePostResponse = ExecuteToolApiV1AgentsToolsExecutePostResponses[keyof ExecuteToolApiV1AgentsToolsExecutePostResponses];
